# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_mentor_db
spring.datasource.username=aiuser
spring.datasource.password=2020010b051
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT Config
# ===============================
app.jwt.secret=replace_with_a_very_long_random_secret
app.jwt.expiration=86400000

# ===============================
# Server Port
# ===============================
server.port=8081



